version: '3'

services:
  mongo:
    image: mongo
    container_name: hobbyhub_mongo
    restart: always
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: hobbyhub_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: hobbyhub_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
